import datasets

_CITATION = """\
@InProceedings{huggingface:dataset,
title = {Nanostructures dataset},
year={2023}
}
"""

_DESCRIPTION = """\
Demo dataset for testing or showing image-text capabilities.
"""
_HOMEPAGE = "https://huggingface.co/datasets/purpletyoma/image-demo"

_LICENSE = ""

_REPO = "https://huggingface.co/datasets/purpletyoma/image-demo"

description = [{'Ca ion, mM': 81,
  'CO3 ion, mM': 22,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.34,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.43,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 5340},
 {'Ca ion, mM': 133,
  'CO3 ion, mM': 22,
  'HCO3 ion, mM': 240,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '3',
  'Polymer, % wt.': 0.38,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 500},
 {'Ca ion, mM': 69,
  'CO3 ion, mM': 203,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.4,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 2090},
 {'Ca ion, mM': 50,
  'CO3 ion, mM': 46,
  'HCO3 ion, mM': 31,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.32,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 1729},
 {'Ca ion, mM': 179,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 280,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '25',
  'Polymer, % wt.': 0.88,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 520},
 {'Ca ion, mM': 65,
  'CO3 ion, mM': 136,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.25,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.2,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 510},
 {'Ca ion, mM': 194,
  'CO3 ion, mM': 63,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '3',
  'Polymer, % wt.': 0.6,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 2070},
 {'Ca ion, mM': 295,
  'CO3 ion, mM': 260,
  'HCO3 ion, mM': 83,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.28,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 1699},
 {'Ca ion, mM': 249,
  'CO3 ion, mM': 225,
  'HCO3 ion, mM': 30,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.08,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 1690},
 {'Ca ion, mM': 80,
  'CO3 ion, mM': 50,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '25',
  'Polymer, % wt.': 0.68,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 1165},
 {'Ca ion, mM': 216,
  'CO3 ion, mM': 144,
  'HCO3 ion, mM': 200,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.73,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1290},
 {'Ca ion, mM': 59,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 131,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.14,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 1770},
 {'Ca ion, mM': 52,
  'CO3 ion, mM': 71,
  'HCO3 ion, mM': 56,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '17',
  'Polymer, % wt.': 0.5,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 240},
 {'Ca ion, mM': 175,
  'CO3 ion, mM': 71,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.6,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 2049},
 {'Ca ion, mM': 73,
  'CO3 ion, mM': 184,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '3',
  'Polymer, % wt.': 0.27,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 230},
 {'Ca ion, mM': 31,
  'CO3 ion, mM': 219,
  'HCO3 ion, mM': 23,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '25',
  'Polymer, % wt.': 0.09,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1279},
 {'Ca ion, mM': 17,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 100,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.85,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 1144},
 {'Ca ion, mM': 26,
  'CO3 ion, mM': 39,
  'HCO3 ion, mM': 36,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.5,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1270},
 {'Ca ion, mM': 220,
  'CO3 ion, mM': 77,
  'HCO3 ion, mM': 52,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '80',
  'Polymer, % wt.': 0.26,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1260},
 {'Ca ion, mM': 255,
  'CO3 ion, mM': 156,
  'HCO3 ion, mM': 18,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '17',
  'Polymer, % wt.': 0.4,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1219},
 {'Ca ion, mM': 35,
  'CO3 ion, mM': 67,
  'HCO3 ion, mM': 32,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.65,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 1210},
 {'Ca ion, mM': 57,
  'CO3 ion, mM': 140,
  'HCO3 ion, mM': 200,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '25',
  'Polymer, % wt.': 0.16,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 480},
 {'Ca ion, mM': 124,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 272,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.08,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 770,
  'Temperature, C': 76,
  'Synthesis time': 2079},
 {'Ca ion, mM': 90,
  'CO3 ion, mM': 10,
  'HCO3 ion, mM': 72,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '3',
  'Polymer, % wt.': 0.14,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 68,
  'Synthesis time': 1125},
 {'Ca ion, mM': 96,
  'CO3 ion, mM': 26,
  'HCO3 ion, mM': 241,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '17',
  'Polymer, % wt.': 0.23,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 58,
  'Synthesis time': 1759},
 {'Ca ion, mM': 85,
  'CO3 ion, mM': 81,
  'HCO3 ion, mM': 28,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 10.0,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2660},
 {'Ca ion, mM': 74,
  'CO3 ion, mM': 184,
  'HCO3 ion, mM': 44,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 20.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 300},
 {'Ca ion, mM': 94,
  'CO3 ion, mM': 95,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 70.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 290},
 {'Ca ion, mM': 33,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 185,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 16.4,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2430},
 {'Ca ion, mM': 351,
  'CO3 ion, mM': 236,
  'HCO3 ion, mM': 180,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 7.8,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 330},
 {'Ca ion, mM': 49,
  'CO3 ion, mM': 82,
  'HCO3 ion, mM': 243,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 17.4,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2690},
 {'Ca ion, mM': 285,
  'CO3 ion, mM': 120,
  'HCO3 ion, mM': 166,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 10.8,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 280},
 {'Ca ion, mM': 63,
  'CO3 ion, mM': 159,
  'HCO3 ion, mM': 25,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 8.8,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2649},
 {'Ca ion, mM': 189,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 181,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 41.0,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2420},
 {'Ca ion, mM': 154,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 42,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 23.2,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2409},
 {'Ca ion, mM': 78,
  'CO3 ion, mM': 58,
  'HCO3 ion, mM': 82,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 7.0,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2400},
 {'Ca ion, mM': 87,
  'CO3 ion, mM': 350,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 14.0,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2679},
 {'Ca ion, mM': 117,
  'CO3 ion, mM': 285,
  'HCO3 ion, mM': 110,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 4.6,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 230},
 {'Ca ion, mM': 203,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 100,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 56.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 220},
 {'Ca ion, mM': 58,
  'CO3 ion, mM': 96,
  'HCO3 ion, mM': 48,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 33.8,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2379},
 {'Ca ion, mM': 26,
  'CO3 ion, mM': 96,
  'HCO3 ion, mM': 170,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 16.8,
  'Stirring, rpm': 440,
  'Temperature, C': 55,
  'Synthesis time': 2370},
 {'Ca ion, mM': 162,
  'CO3 ion, mM': 44,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 34.0,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 1039},
 {'Ca ion, mM': 214,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 140,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 20.0,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 380},
 {'Ca ion, mM': 59,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 109,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 3.2,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 320},
 {'Ca ion, mM': 116,
  'CO3 ion, mM': 68,
  'HCO3 ion, mM': 15,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 18.2,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 1030},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 23,
  'HCO3 ion, mM': 150,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 10.6,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 1020},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 129,
  'HCO3 ion, mM': 192,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 8.4,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 370},
 {'Ca ion, mM': 262,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 213,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 18.0,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2709},
 {'Ca ion, mM': 79,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 96,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 11.4,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 360},
 {'Ca ion, mM': 82,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 18,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 42.0,
  'Stirring, rpm': 350,
  'Temperature, C': 50,
  'Synthesis time': 350},
 {'Ca ion, mM': 46,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 155,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 44.0,
  'Stirring, rpm': 0,
  'Temperature, C': 30,
  'Synthesis time': 2700},
 {'Ca ion, mM': 146,
  'CO3 ion, mM': 146,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 40.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 270},
 {'Ca ion, mM': 379,
  'CO3 ion, mM': 112,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 24.2,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 1009},
 {'Ca ion, mM': 324,
  'CO3 ion, mM': 28,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 37.6,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 990},
 {'Ca ion, mM': 87,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 20,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 27.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 260},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 180,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 8.0,
  'Stirring, rpm': 0,
  'Temperature, C': 37,
  'Synthesis time': 240},
 {'Ca ion, mM': 22,
  'CO3 ion, mM': 146,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 6.2,
  'Stirring, rpm': 250,
  'Temperature, C': 35,
  'Synthesis time': 979},
 {'Ca ion, mM': 37,
  'CO3 ion, mM': 98,
  'HCO3 ion, mM': 40,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.29,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 8.0,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1144},
 {'Ca ion, mM': 37,
  'CO3 ion, mM': 84,
  'HCO3 ion, mM': 109,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Triton X-100',
  'Surfactant, % wt.': 2.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 8.4,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 865},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 40,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.07,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 18.6,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 855},
 {'Ca ion, mM': 88,
  'CO3 ion, mM': 126,
  'HCO3 ion, mM': 67,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.16,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 13.4,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1135},
 {'Ca ion, mM': 330,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 205,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.13,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 17.2,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 275},
 {'Ca ion, mM': 290,
  'CO3 ion, mM': 61,
  'HCO3 ion, mM': 104,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Triton X-100',
  'Surfactant, % wt.': 5.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 12.6,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 325},
 {'Ca ion, mM': 161,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 31,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.19,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 40.0,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1125},
 {'Ca ion, mM': 65,
  'CO3 ion, mM': 185,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.31,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 8.6,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 845},
 {'Ca ion, mM': 38,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 106,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.23,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 23.4,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1114},
 {'Ca ion, mM': 50,
  'CO3 ion, mM': 74,
  'HCO3 ion, mM': 186,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 1.18,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 7.8,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 255},
 {'Ca ion, mM': 39,
  'CO3 ion, mM': 243,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.21,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 34.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 195},
 {'Ca ion, mM': 122,
  'CO3 ion, mM': 205,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.12,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 18.4,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1105},
 {'Ca ion, mM': 78,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 255,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 1.25,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 5.2,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1095},
 {'Ca ion, mM': 86,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 155,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.27,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 4.2,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 185},
 {'Ca ion, mM': 176,
  'CO3 ion, mM': 31,
  'HCO3 ion, mM': 53,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.17,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 42.0,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1075},
 {'Ca ion, mM': 97,
  'CO3 ion, mM': 58,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.17,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 28.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 175},
 {'Ca ion, mM': 75,
  'CO3 ion, mM': 137,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.17,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 17.2,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1155},
 {'Ca ion, mM': 140,
  'CO3 ion, mM': 111,
  'HCO3 ion, mM': 111,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.39,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 28.4,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1045},
 {'Ca ion, mM': 32,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 180,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Triton X-100',
  'Surfactant, % wt.': 3.9,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 13.4,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 905},
 {'Ca ion, mM': 40,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 64,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.09,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 46.0,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1035},
 {'Ca ion, mM': 55,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 145,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Triton X-100',
  'Surfactant, % wt.': 2.5,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 13.2,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 895},
 {'Ca ion, mM': 110,
  'CO3 ion, mM': 81,
  'HCO3 ion, mM': 112,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.37,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 35.4,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 300},
 {'Ca ion, mM': 44,
  'CO3 ion, mM': 159,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.06,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 29.0,
  'Stirring, rpm': 590,
  'Temperature, C': 19,
  'Synthesis time': 885},
 {'Ca ion, mM': 146,
  'CO3 ion, mM': 131,
  'HCO3 ion, mM': 36,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.28,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 9.0,
  'Stirring, rpm': 690,
  'Temperature, C': 22,
  'Synthesis time': 940},
 {'Ca ion, mM': 22,
  'CO3 ion, mM': 251,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.87,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 32.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 285},
 {'Ca ion, mM': 32,
  'CO3 ion, mM': 51,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.93,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 24.0,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1065},
 {'Ca ion, mM': 43,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 63,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.16,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 12.2,
  'Stirring, rpm': 0,
  'Temperature, C': 26,
  'Synthesis time': 1054},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 140,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.09,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 17.4,
  'Stirring, rpm': 690,
  'Temperature, C': 22,
  'Synthesis time': 930},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 71,
  'HCO3 ion, mM': 77,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.12,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 34.0,
  'Stirring, rpm': 690,
  'Temperature, C': 22,
  'Synthesis time': 915},
 {'Ca ion, mM': 105,
  'CO3 ion, mM': 206,
  'HCO3 ion, mM': 97,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.27,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 27.0,
  'Stirring, rpm': 690,
  'Temperature, C': 22,
  'Synthesis time': 905},
 {'Ca ion, mM': 90,
  'CO3 ion, mM': 142,
  'HCO3 ion, mM': 167,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.44,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 5.8,
  'Stirring, rpm': 690,
  'Temperature, C': 22,
  'Synthesis time': 895},
 {'Ca ion, mM': 60,
  'CO3 ion, mM': 55,
  'HCO3 ion, mM': 60,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1290},
 {'Ca ion, mM': 43,
  'CO3 ion, mM': 140,
  'HCO3 ion, mM': 44,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1279},
 {'Ca ion, mM': 95,
  'CO3 ion, mM': 80,
  'HCO3 ion, mM': 88,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 2010},
 {'Ca ion, mM': 142,
  'CO3 ion, mM': 80,
  'HCO3 ion, mM': 190,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 2000},
 {'Ca ion, mM': 182,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 97,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 450},
 {'Ca ion, mM': 163,
  'CO3 ion, mM': 42,
  'HCO3 ion, mM': 91,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1270},
 {'Ca ion, mM': 86,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 69,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 440},
 {'Ca ion, mM': 209,
  'CO3 ion, mM': 26,
  'HCO3 ion, mM': 144,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1989},
 {'Ca ion, mM': 65,
  'CO3 ion, mM': 170,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1260},
 {'Ca ion, mM': 53,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 77,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 430},
 {'Ca ion, mM': 172,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 165,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 420},
 {'Ca ion, mM': 110,
  'CO3 ion, mM': 83,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1980},
 {'Ca ion, mM': 41,
  'CO3 ion, mM': 66,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1249},
 {'Ca ion, mM': 42,
  'CO3 ion, mM': 120,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1970},
 {'Ca ion, mM': 136,
  'CO3 ion, mM': 165,
  'HCO3 ion, mM': 28,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1240},
 {'Ca ion, mM': 36,
  'CO3 ion, mM': 81,
  'HCO3 ion, mM': 140,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 410},
 {'Ca ion, mM': 120,
  'CO3 ion, mM': 55,
  'HCO3 ion, mM': 32,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1959},
 {'Ca ion, mM': 109,
  'CO3 ion, mM': 20,
  'HCO3 ion, mM': 32,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 400},
 {'Ca ion, mM': 52,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 175,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1230},
 {'Ca ion, mM': 66,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 56,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1950},
 {'Ca ion, mM': 82,
  'CO3 ion, mM': 36,
  'HCO3 ion, mM': 79,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 380},
 {'Ca ion, mM': 90,
  'CO3 ion, mM': 185,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1210},
 {'Ca ion, mM': 185,
  'CO3 ion, mM': 185,
  'HCO3 ion, mM': 61,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 23,
  'Synthesis time': 370},
 {'Ca ion, mM': 220,
  'CO3 ion, mM': 46,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1200},
 {'Ca ion, mM': 97,
  'CO3 ion, mM': 147,
  'HCO3 ion, mM': 14,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1189},
 {'Ca ion, mM': 86,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 18,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1180},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 57,
  'HCO3 ion, mM': 110,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1950},
 {'Ca ion, mM': 38,
  'CO3 ion, mM': 92,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 1170},
 {'Ca ion, mM': 146,
  'CO3 ion, mM': 167,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1940},
 {'Ca ion, mM': 105,
  'CO3 ion, mM': 74,
  'HCO3 ion, mM': 33,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1929},
 {'Ca ion, mM': 63,
  'CO3 ion, mM': 67,
  'HCO3 ion, mM': 53,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1920},
 {'Ca ion, mM': 25,
  'CO3 ion, mM': 60,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 330,
  'Temperature, C': 43,
  'Synthesis time': 1909},
 {'Ca ion, mM': 77,
  'CO3 ion, mM': 77,
  'HCO3 ion, mM': 43,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 14.6,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 1030},
 {'Ca ion, mM': 62,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 94,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.29,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 8.2,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 1020},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 63,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '20',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 13.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1225},
 {'Ca ion, mM': 51,
  'CO3 ion, mM': 55,
  'HCO3 ion, mM': 55,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.02,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 7.4,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 350},
 {'Ca ion, mM': 82,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 64,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.05,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 8.6,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1150},
 {'Ca ion, mM': 83,
  'CO3 ion, mM': 22,
  'HCO3 ion, mM': 83,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '20',
  'Polymer, % wt.': 0.13,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 4.8,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 600},
 {'Ca ion, mM': 95,
  'CO3 ion, mM': 28,
  'HCO3 ion, mM': 66,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '70',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 18.4,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 340},
 {'Ca ion, mM': 100,
  'CO3 ion, mM': 23,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '20',
  'Polymer, % wt.': 0.3,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 2.6,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 330},
 {'Ca ion, mM': 46,
  'CO3 ion, mM': 50,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.12,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 3.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1215},
 {'Ca ion, mM': 50,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 35,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.4,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 5.0,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1140},
 {'Ca ion, mM': 69,
  'CO3 ion, mM': 68,
  'HCO3 ion, mM': 16,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.12,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 14.2,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1129},
 {'Ca ion, mM': 63,
  'CO3 ion, mM': 78,
  'HCO3 ion, mM': 23,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 7.8,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 320},
 {'Ca ion, mM': 62,
  'CO3 ion, mM': 89,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '70',
  'Polymer, % wt.': 0.12,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 3.2,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1204},
 {'Ca ion, mM': 38,
  'CO3 ion, mM': 96,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.14,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 20.0,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 300},
 {'Ca ion, mM': 46,
  'CO3 ion, mM': 66,
  'HCO3 ion, mM': 62,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.02,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 4.4,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 590},
 {'Ca ion, mM': 72,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 40,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.31,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 9.8,
  'Stirring, rpm': 0,
  'Temperature, C': 47,
  'Synthesis time': 290},
 {'Ca ion, mM': 72,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 72,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.1,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 13.6,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 1009},
 {'Ca ion, mM': 84,
  'CO3 ion, mM': 16,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.44,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 18.4,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1120},
 {'Ca ion, mM': 91,
  'CO3 ion, mM': 16,
  'HCO3 ion, mM': 80,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.29,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 14.2,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 580},
 {'Ca ion, mM': 97,
  'CO3 ion, mM': 64,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.07,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 8.6,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 1000},
 {'Ca ion, mM': 97,
  'CO3 ion, mM': 79,
  'HCO3 ion, mM': 100,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.1,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 4.6,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1110},
 {'Ca ion, mM': 81,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 28,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.19,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Isopropyl alcohol',
  'Solvent, % vol.': 16.6,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 570},
 {'Ca ion, mM': 66,
  'CO3 ion, mM': 94,
  'HCO3 ion, mM': 35,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.01,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'tert-Butanol',
  'Solvent, % vol.': 17.6,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 549},
 {'Ca ion, mM': 56,
  'CO3 ion, mM': 88,
  'HCO3 ion, mM': 13,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.24,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 17.0,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 979},
 {'Ca ion, mM': 68,
  'CO3 ion, mM': 72,
  'HCO3 ion, mM': 29,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '70',
  'Polymer, % wt.': 0.41,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Methyl alcohol',
  'Solvent, % vol.': 11.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1195},
 {'Ca ion, mM': 50,
  'CO3 ion, mM': 53,
  'HCO3 ion, mM': 11,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.42,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 10.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1185},
 {'Ca ion, mM': 50,
  'CO3 ion, mM': 71,
  'HCO3 ion, mM': 34,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.11,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 9.6,
  'Stirring, rpm': 500,
  'Temperature, C': 41,
  'Synthesis time': 1099},
 {'Ca ion, mM': 29,
  'CO3 ion, mM': 87,
  'HCO3 ion, mM': 53,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.02,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 9.2,
  'Stirring, rpm': 0,
  'Temperature, C': 70,
  'Synthesis time': 540},
 {'Ca ion, mM': 36,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 71,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '70',
  'Polymer, % wt.': 0.23,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Propylene glycol',
  'Solvent, % vol.': 18.8,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1170},
 {'Ca ion, mM': 44,
  'CO3 ion, mM': 66,
  'HCO3 ion, mM': 88,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.08,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Ethylene glycol',
  'Solvent, % vol.': 6.4,
  'Stirring, rpm': 400,
  'Temperature, C': 28,
  'Synthesis time': 970},
 {'Ca ion, mM': 88,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 58,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '360',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'Dimethylformamide',
  'Solvent, % vol.': 6.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1159},
 {'Ca ion, mM': 93,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 66,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.33,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': '1-Hexanol',
  'Solvent, % vol.': 20.0,
  'Stirring, rpm': 0,
  'Temperature, C': 64,
  'Synthesis time': 1150},
 {'Ca ion, mM': 80,
  'CO3 ion, mM': 33,
  'HCO3 ion, mM': 147,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.3,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.8,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2090},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 23,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.45,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.32,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 535},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 44,
  'HCO3 ion, mM': 76,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.8,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.03,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2079},
 {'Ca ion, mM': 125,
  'CO3 ion, mM': 67,
  'HCO3 ion, mM': 97,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.15,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.57,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 300},
 {'Ca ion, mM': 149,
  'CO3 ion, mM': 185,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 1.2,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.44,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2070},
 {'Ca ion, mM': 64,
  'CO3 ion, mM': 230,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.31,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.23,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 525},
 {'Ca ion, mM': 56,
  'CO3 ion, mM': 75,
  'HCO3 ion, mM': 6,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 1.1,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.14,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 515},
 {'Ca ion, mM': 39,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 200,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.3,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.05,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 290},
 {'Ca ion, mM': 89,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 200,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.55,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.08,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2060},
 {'Ca ion, mM': 100,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 59,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.9,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 505},
 {'Ca ion, mM': 198,
  'CO3 ion, mM': 75,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.02,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.08,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2049},
 {'Ca ion, mM': 93,
  'CO3 ion, mM': 32,
  'HCO3 ion, mM': 4,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.8,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.05,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 495},
 {'Ca ion, mM': 81,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 149,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.15,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.67,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 280},
 {'Ca ion, mM': 162,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 82,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 50,
  'Synthesis time': 270},
 {'Ca ion, mM': 119,
  'CO3 ion, mM': 15,
  'HCO3 ion, mM': 63,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.21,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.49,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 485},
 {'Ca ion, mM': 119,
  'CO3 ion, mM': 10,
  'HCO3 ion, mM': 44,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.42,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.93,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2040},
 {'Ca ion, mM': 69,
  'CO3 ion, mM': 4,
  'HCO3 ion, mM': 212,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.08,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.04,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2030},
 {'Ca ion, mM': 69,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 163,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.1,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.01,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 475},
 {'Ca ion, mM': 59,
  'CO3 ion, mM': 8,
  'HCO3 ion, mM': 96,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.08,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.04,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 470,
  'Temperature, C': 32,
  'Synthesis time': 325},
 {'Ca ion, mM': 86,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 138,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.54,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.02,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 2000},
 {'Ca ion, mM': 163,
  'CO3 ion, mM': 33,
  'HCO3 ion, mM': 76,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.32,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.03,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 415},
 {'Ca ion, mM': 102,
  'CO3 ion, mM': 275,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.35,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.01,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 405},
 {'Ca ion, mM': 116,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 109,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.12,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.12,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 1989},
 {'Ca ion, mM': 90,
  'CO3 ion, mM': 192,
  'HCO3 ion, mM': 6,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.85,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.01,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 470,
  'Temperature, C': 32,
  'Synthesis time': 315},
 {'Ca ion, mM': 70,
  'CO3 ion, mM': 9,
  'HCO3 ion, mM': 49,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.59,
  'Surfactant type': 'Myristyltrimethylammonium bromide',
  'Surfactant, % wt.': 1.36,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 1980},
 {'Ca ion, mM': 60,
  'CO3 ion, mM': 77,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.23,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.03,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 395},
 {'Ca ion, mM': 65,
  'CO3 ion, mM': 3,
  'HCO3 ion, mM': 147,
  'Polymer type': 'PEI',
  'Polymer Mwt, kDa': '75',
  'Polymer, % wt.': 0.09,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.06,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 1970},
 {'Ca ion, mM': 135,
  'CO3 ion, mM': 132,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PSS',
  'Polymer Mwt, kDa': '1,000',
  'Polymer, % wt.': 0.95,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.08,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 385},
 {'Ca ion, mM': 85,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 85,
  'Polymer type': 'PAA',
  'Polymer Mwt, kDa': '2.10',
  'Polymer, % wt.': 0.03,
  'Surfactant type': 'Hexadecyltrimethylammonium bromide',
  'Surfactant, % wt.': 0.1,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 730,
  'Temperature, C': 46,
  'Synthesis time': 375},
 {'Ca ion, mM': 112,
  'CO3 ion, mM': 49,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 0.5,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.4,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 470,
  'Temperature, C': 32,
  'Synthesis time': 285},
 {'Ca ion, mM': 89,
  'CO3 ion, mM': 5,
  'HCO3 ion, mM': 235,
  'Polymer type': 'PVP',
  'Polymer Mwt, kDa': '40',
  'Polymer, % wt.': 0.02,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 1.3,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 470,
  'Temperature, C': 32,
  'Synthesis time': 275},
 {'Ca ion, mM': 33,
  'CO3 ion, mM': 110,
  'HCO3 ion, mM': 0,
  'Polymer type': 'PEG',
  'Polymer Mwt, kDa': '8',
  'Polymer, % wt.': 1.1,
  'Surfactant type': 'Sodium dodecylsulfate',
  'Surfactant, % wt.': 0.31,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 65,
  'Synthesis time': 1959},
 {'Ca ion, mM': 79,
  'CO3 ion, mM': 41,
  'HCO3 ion, mM': 250,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 220},
 {'Ca ion, mM': 72,
  'CO3 ion, mM': 170,
  'HCO3 ion, mM': 180,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 970},
 {'Ca ion, mM': 360,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 65,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 210},
 {'Ca ion, mM': 43,
  'CO3 ion, mM': 64,
  'HCO3 ion, mM': 43,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 960},
 {'Ca ion, mM': 52,
  'CO3 ion, mM': 115,
  'HCO3 ion, mM': 30,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 950},
 {'Ca ion, mM': 325,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 150,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 200},
 {'Ca ion, mM': 275,
  'CO3 ion, mM': 87,
  'HCO3 ion, mM': 171,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 51,
  'Synthesis time': 909},
 {'Ca ion, mM': 303,
  'CO3 ion, mM': 100,
  'HCO3 ion, mM': 41,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2900},
 {'Ca ion, mM': 88,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 205,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 51,
  'Synthesis time': 900},
 {'Ca ion, mM': 98,
  'CO3 ion, mM': 143,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 189},
 {'Ca ion, mM': 230,
  'CO3 ion, mM': 240,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 940},
 {'Ca ion, mM': 194,
  'CO3 ion, mM': 290,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 930},
 {'Ca ion, mM': 160,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 63,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 920},
 {'Ca ion, mM': 29,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 76,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 180},
 {'Ca ion, mM': 18,
  'CO3 ion, mM': 385,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 51,
  'Synthesis time': 890},
 {'Ca ion, mM': 115,
  'CO3 ion, mM': 50,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 170},
 {'Ca ion, mM': 44,
  'CO3 ion, mM': 255,
  'HCO3 ion, mM': 185,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 160},
 {'Ca ion, mM': 100,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 172,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 710},
 {'Ca ion, mM': 218,
  'CO3 ion, mM': 285,
  'HCO3 ion, mM': 33,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 51,
  'Synthesis time': 880},
 {'Ca ion, mM': 256,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 36,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 150},
 {'Ca ion, mM': 76,
  'CO3 ion, mM': 34,
  'HCO3 ion, mM': 40,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 700},
 {'Ca ion, mM': 93,
  'CO3 ion, mM': 58,
  'HCO3 ion, mM': 82,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 140},
 {'Ca ion, mM': 182,
  'CO3 ion, mM': 62,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2889},
 {'Ca ion, mM': 148,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 100,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 0,
  'Temperature, C': 31,
  'Synthesis time': 129},
 {'Ca ion, mM': 100,
  'CO3 ion, mM': 330,
  'HCO3 ion, mM': 154,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 690},
 {'Ca ion, mM': 84,
  'CO3 ion, mM': 274,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2880},
 {'Ca ion, mM': 68,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 240,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 680},
 {'Ca ion, mM': 177,
  'CO3 ion, mM': 219,
  'HCO3 ion, mM': 31,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 820,
  'Temperature, C': 35,
  'Synthesis time': 669},
 {'Ca ion, mM': 216,
  'CO3 ion, mM': 78,
  'HCO3 ion, mM': 62,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2874},
 {'Ca ion, mM': 27,
  'CO3 ion, mM': 87,
  'HCO3 ion, mM': 0,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2865},
 {'Ca ion, mM': 21,
  'CO3 ion, mM': 0,
  'HCO3 ion, mM': 66,
  'Polymer type': 'None',
  'Polymer Mwt, kDa': '0',
  'Polymer, % wt.': 0.0,
  'Surfactant type': 'None',
  'Surfactant, % wt.': 0.0,
  'Solvent type': 'None',
  'Solvent, % vol.': 0.0,
  'Stirring, rpm': 620,
  'Temperature, C': 68,
  'Synthesis time': 2855}]

class ImageSet(datasets.GeneratorBasedBuilder):
    """Small sample of image-text pairs"""

    def _info(self):
        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=datasets.Features(
                {
                    'text': datasets.Value("string"),
                    'image': datasets.Image(),
                }
            ),
            supervised_keys=None,
            homepage=_HOMEPAGE,
            citation=_CITATION,
        )

    def _split_generators(self, dl_manager):
        images_archive = dl_manager.download(f"{_REPO}/resolve/main/images.tar.gz")
        image_iters = dl_manager.iter_archive(images_archive)
        return [
            datasets.SplitGenerator(
                name=datasets.Split.TRAIN,
                gen_kwargs={
                    "images": image_iters
                }
            ),
        ]

    def _generate_examples(self, images):
        """ This function returns the examples in the raw (text) form."""
        
        for idx, (filepath, image) in enumerate(images):
            
            yield idx, {
                "image": {"path": filepath, "bytes": image.read()},
                "text": description[idx],
            }
            idx += 1
